### ISSUE TITLE
Unable to install via pip3

### ISSUE THREAD

**Issue by matlegit** [Ejhfast/meta#1]
Hey Ethan,

This is Matt, I emailed you guys yesterday about the slides. I've been playing around with Meta and couldn't seem to install it through pip last night. 

Instead I installed it from source [here](https://pypi.python.org/pypi/metalang) which worked.
I'm running Python 3.4.3 on Ubuntu 14.04.5 Trusty.

Here is the traceback, which a colleague of mine also got:

matt@ubuntu-trusty-64:~$ pip3 install metalang
Downloading/unpacking metalang
  Could not find a version that satisfies the requirement metalang (from versions: 0.48a)
Cleaning up...
No distributions matching the version for metalang
Storing debug log for failure in /home/vagrant/.pip/pip.log

**Comment by matlegit** [comment]
Also, when I installed it from source, I had to update my `requests` library with `sudo pip3 install --upgrade requests`

**Comment by matlegit** [comment]
Debug log for pip3:

Downloading/unpacking metalang
  Getting page https://pypi.python.org/simple/metalang/
  URLs to search for versions for metalang:
  * https://pypi.python.org/simple/metalang/
  Analyzing links from page https://pypi.python.org/simple/metalang/
    Found link https://pypi.python.org/packages/d0/a0/c01aff4dc9a536ab89b79f98904716235a2a9d2731688d17951ec6f2a96c/metalang-0.48a.tar.gz#md5=53ac96cb3b16cff561696e92d2e3478d (from https://pypi.python.org/simple/metalang/), version: 0.48a
  Ignoring link https://pypi.python.org/packages/d0/a0/c01aff4dc9a536ab89b79f98904716235a2a9d2731688d17951ec6f2a96c/metalang-0.48a.tar.gz#md5=53ac96cb3b16cff561696e92d2e3478d (from https://pypi.python.org/simple/metalang/), version 0.48a is a pre-release (use --pre to allow).
  Could not find a version that satisfies the requirement metalang (from versions: 0.48a)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
No distributions matching the version for metalang
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
pip.exceptions.DistributionNotFound: No distributions matching the version for metalang

**Comment by Nokiand** [comment]
Trying to use metalang, interpret-compile test/context.py error:
Ipad $ python meta-master/test/context.py
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/3CA7E060-F478-456D-A072-BFA0B032F708/Documents/site-packages3/numpy/__init__.py", line 127, in <module>
    from numpy.__config__ import show as show_config
ModuleNotFoundError: No module named 'numpy.__config__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "meta-master/test/context.py", line 5, in <module>
    from metalang import Meta
  File "/var/mobile/Containers/Data/Application/3CA7E060-F478-456D-A072-BFA0B032F708/Documents/site-packages3/metalang/__init__.py", line 1, in <module>
    from .core import Meta
  File "/var/mobile/Containers/Data/Application/3CA7E060-F478-456D-A072-BFA0B032F708/Documents/site-packages3/metalang/core.py", line 5, in <module>
    import numpy as np
  File "/var/mobile/Containers/Data/Application/3CA7E060-F478-456D-A072-BFA0B032F708/Documents/site-packages3/numpy/__init__.py", line 132, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there.

**Comment by Nokiand** [comment]
Ipad $ python -m pip install metalang
Running from numpy source directory.
Approximating pkg_resources ...
Querying PyPI ... 
Downloading package ...

Extracting archive file ...
Reading gzip file.
Extracting files.
Archive extracted.
Running setup file ...
Package installed: metalang
Installing dependency: numpy (required by: metalang)
Querying PyPI ... 
Downloading package ...

Extracting archive file ...
Running setup file ...
TypeError('__mro_entries__ must return a tuple')
Failed to run setup.py
Fall back to directory guessing ...
Package installed: numpy
Installing dependency: dill (required by: metalang)
Querying PyPI ... 
Downloading package ...

Installing wheel: dill-0.3.5.1-py2.py3-none-any.whl...
Package installed: dill
Installing dependency: pymongo (required by: metalang)
Querying PyPI ... 
Downloading package ...

Extracting archive file ...
Reading gzip file.
Extracting files.
Archive extracted.
Running setup file ...
TypeError('__mro_entries__ must return a tuple')
Failed to run setup.py
Fall back to directory guessing ...
Package installed: pymongo
Dependency available in Pyto bundle : requests
Installing dependency: typing (required by: metalang)
Querying PyPI ... 
Downloading package ...

Extracting archive file ...
Reading gzip file.
Extracting files.
Archive extracted.
Running setup file ...
FileNotFoundError(2, 'No such file or directory')
Failed to run setup.py
Fall back to directory guessing ...
Error: Cannot locate packages. Manual installation required.
